### ISSUE TITLE
Termux commands

### ISSUE THREAD

**Issue by TheDidek** [nhirokinet/bluelineconsole#104]
I have an idea, that it would be awesome to integrate this app with Termux, to execute commands with output just like we can do pinging 😁. Termux app already have severial plugins. I don't know how difficult it would be, but I wanted to share that idea.

**Comment by nhirokinet** [comment]
> Termux app already have severial plugins.

As long as I read none of them seems to be related with integration with other apps. Did you find something that seems to be related with integration?
https://wiki.termux.com/wiki/Addons

In my opinion, as Termux perspective, accepting commands from other apps is something dangerous and at least it needs special API to safely handle the command. Is there some documents which seems to describe this kind of interface?

**Comment by nhirokinet** [comment]
As long as Termux does not allow access from other apps, it is not a Blue Line Console issue for now.
