### ISSUE TITLE
[Feature Request] Add the privacy oriented search engines (MetaGer, Qwant, Searx)

### ISSUE THREAD

**Issue by machiav3lli** [nhirokinet/bluelineconsole#11]
I think the title explains it most clearly.

**Comment by nhirokinet** [comment]
Maybe I should think whether adding an option to add search engine URLs by users themselves, or just adding engines. I will comment after some consideration.
Just for now DuckDuckGo is already included. I know you are giving me a comment because it is not enough options. Let me have a time.

**Comment by meain** [comment]
I personally think it would be better to give an option to add custom search engines from the user end. This will let them search even some obscure pages and not just popular search engines.

**Comment by nhirokinet** [comment]
Configuration for custom search engine was added in #25 , and was deployed as version 1.0.9. You can use search engines you like.

Preset may be adjusted according to market share or other reasons, but for now this purpose can be archived with simple configuration.
