### ISSUE TITLE
[Feature Request] Favorite search engine

### ISSUE THREAD

**Issue by machiav3lli** [nhirokinet/bluelineconsole#12]
Add option for a favorite search engine, which is called when there's no local results anymore(without the need for its prefix).

**Comment by nhirokinet** [comment]
Added default search engine preferences in #35 released it in version 1.0.11.

Not to confuse in a case expecting no local result but actually some were found, default search engine is added always at the bottom when set, rather than only when there's no local results.

**Comment by machiav3lli** [comment]
Great, thanks
