### ISSUE TITLE
[Feature Request] Command to List All Apps

### ISSUE THREAD

**Issue by daffydock** [nhirokinet/bluelineconsole#163]
I have come to embrace your app as my default launcher and I want to take this opportunity to thank you for developing  it. It is a great app and a pleasure to use due to its search capabilities. I have added numerous search engines and the capability of being able to bring it anywhere saves a lot of time. 

It is awesome that I can also see widget data on a number of my apps straight from the search box, without having to into the app themselves. Like calendar, email, reddit, etc. It's Incredibly useful. 

As such, one feature I would like to request to see implemented would be a simple way to see/scroll all apps. Like a command, like say, _List_ or _Show All_  or _All Apps_, or something to that effect. My main reason is that in that way, anyone can go through all apps in case they want to see them, or delete them. In case we forget the existence of little used apps. Thank you, again.

**Comment by nhirokinet** [comment]
Simple workaround available now is just single period (".". without quotes), which normal app is not missed. I will think of better way.

**Comment by daffydock** [comment]
Using "." does exactly what I originally wanted. Please, do not change it. Leave it as it stands. It is both simple and straightforward.

One detail I noticed however, is that once you allow for Contacts to be searchable, most email addresses and many names may have a ".", in them. Apps do show, but do so all the way at the bottom of the list, after the contacts which slows down the user experience if the user has a lot of contacts. 

If perhaps "." could be used to see _apps_ only and something like ".#" or ".." to only see _contacts_, only?

**Comment by nhirokinet** [comment]
"." is not a special command, it is just hitting to the package name which is normally formed like "net.nhiroki.bluelineconsole". So both for e-mail and application search, this behavior is not subject to change.

I'm thinking to add a command that hits all apps and less likely to hit another items.

**Comment by nhirokinet** [comment]
I added "all_apps" command in Version 1.2.8.

This time the status in Google Play is "in review", so availability on Google Play and F-Droid will take a time according to each store's policy.

**Comment by daffydock** [comment]
@nhirokinet 

Ah, I see.

**Comment by daffydock** [comment]
@nhirokinet 

I use F-Droid. 
And no worries. I will wait. 

Thank you.
