### ISSUE TITLE
[Feature request] adding input history functionality

### ISSUE THREAD

**Issue by amalgame21** [nhirokinet/bluelineconsole#178]
like bash
pressing arrow up key to show previous input history
pressing arrow down to show next input history
setting to limit the number of history stored, 0 to disable the feature
setting to enable/disable above functionalty since someone may want to use arrow key to cycle through the search result like what arrow key is doing now, but not cycle through history
it is very useful if some frequently used app needed to be launched repeatedly, and sometimes just suddenly forgot the start of some app's name

seems demand too much haha
just some crazy idea, don't mind

**Comment by amalgame21** [comment]
also the "history" command to display list of input history
and the ability to input them again, or delete them specifically 
and ability to clean all input history

since sometimes the input is very long (like search engine keyword)
and it may involve some special characters which is hard to type
make it time consuming to type again

**Comment by nhirokinet** [comment]
duplicated #89
