### ISSUE TITLE
[Feature Request] App suggestions before typing

### ISSUE THREAD

**Issue by 2br-2b** [nhirokinet/bluelineconsole#194]
Hey,

I'm trying this out to see if combining this with Tasker (using Tasker as the virtual assistant to launch this app) is viable for my daily driving.

My main complaint so far is that, when the app first opens, it looks like this:
![Screenshot_20211114-234356](https://user-images.githubusercontent.com/43968991/141723791-ebda8729-38e7-4054-aa69-8f0a607d8dd1.png)

I wish that there was an option to automatically show a few suggestions, determined by recent use, frequency of use, AI, or something else so that I can quickly open Blue Line and sometimes (even if not always) immediately open an app in one tap:
![Screenshot_20211114-234446](https://user-images.githubusercontent.com/43968991/141724075-b422080c-4dec-4599-a666-bbf6843c6326.png)

This should be togglable, since some people will want their prompt blank by default.

It'd also be nice if Blue Line was a virtual assistant app, but that's a completely separate issue…

**Comment by nhirokinet** [comment]
duplicated #89

**Comment by 2br-2b** [comment]
While I think this is related to #89, this would show the second screenshot (based on history, like in #89) when you first launch the console.

**Comment by nhirokinet** [comment]
@2br-2b There may be a little difference, but does it matter as "Feature Request"? Or am I understanding "Feature Request" incorrectly and actually are you trying to implement this?
