### ISSUE TITLE
Icon for virtual assistant app

### ISSUE THREAD

**Issue by J4gQBqqR** [nhirokinet/bluelineconsole#202]
Hi, could you provide an icon in the bottom circle when the blueline console is activated as assistant app?

![Screenshot_20211211-105607_Blue_Line_Console_1](https://user-images.githubusercontent.com/77554817/145683093-bfee4c60-23f9-405a-989e-b0e370f34a45.png)

Thank you.

**Comment by nhirokinet** [comment]
Added in version 1.2.11. Availability on F-droid will take some days until F-droid builds it.
