### ISSUE TITLE
(Feature Request) Fuzzy search uwu

### ISSUE THREAD

**Issue by nihalanand697** [nhirokinet/bluelineconsole#22]
Would you like to add fuzzy search? Its available in some launchers like KISS where you dont need to type each letter of an app name perfectly. To find "newpipe" , "nwp" would also work in such case.
Thanks!

**Comment by nhirokinet** [comment]
There may be an option to change match strategy.

KISS launcher, and GitHub file search (called by "T" shortcut) also seems to match with not sequential substring, like "bde" in "abcdef". If so this is not fuzzy, there is a strict rule for matching, and implementation is not so difficult. To make option I may have to find out how this strategy is called.

**Comment by nihalanand697** [comment]
Yes it is sequential,  i got the term from an app that had it as a feature but anyways name doesnt matter.
I can provide source of two apps known to have this in them
Kiss launcher : https://github.com/Neamar/KISS
And
Faster : https://github.com/ligi/FAST
Thanks

**Comment by nhirokinet** [comment]
Well, when I tried some query in KISS launcher I did not notice, but it seems KISS launcher uses actually "fuzzy" search with ranking, and FAST seems to use Levenshtein distance to checkout.

**Comment by nhirokinet** [comment]
Fuzzy search seems to need some adjustment that is not easy, so I will try to implement "skipped substring" matching like "bde" in "abcde".

**Comment by nhirokinet** [comment]
Added skipped substring in #37 and released in 1.0.11.

**Comment by nihalanand697** [comment]
> Well, when I tried some query in KISS launcher I did not notice, but it seems KISS launcher uses actually "fuzzy" search with ranking, and FAST seems to use Levenshtein distance to checkout. FAST seems to call it as "gap search".

Well yeah kiss does that , but still its no issue even if the sorting is done alphabetically. just the basic gap search (as u call it) will be fine. Thank

**Comment by nihalanand697** [comment]
> Added skipped substring in #37 and released in 1.0.11.

uwu you're awesome

**Comment by nhirokinet** [comment]
Thanks for comment!

**Comment by nhirokinet** [comment]
The reporter's issue seems to be resolved, now I close this issue now.

If someone who see this wants to discuss about better (maybe really fuzzy) strategy, please reopen this or open a new issue.
