### ISSUE TITLE
Feature request: Search engine support query substitute to {} placeholder rather than added at the end of URL

### ISSUE THREAD

**Issue by amalgame21** [nhirokinet/bluelineconsole#247]
Some search engine did not support placing query at the end of URL with other option.
For example, using privacy-oriented Searxng with keyword "bluelineconsole" with other option (Japanese result):
https://searx.tiekoetter.com/search?q=bluelineconsole&language=ja-JP

I tried swapping "language=ja-JP" and "search?q=" to force the query at the end of URL, but it does not work (below not working):
https://searx.tiekoetter.com/language=ja-JP&search?q=bluelineconsole

In qutebrowser, this problem is solved by the syntax substituting query with a {} placeholder like this:
https://searx.tiekoetter.com/search?q={}&language=ja-JP

More information:
https://qutebrowser.org/doc/help/settings.html#url.searchengines

THANKS!!!!

**Comment by nhirokinet** [comment]
Maybe I think in your example you can simply specify https://searx.tiekoetter.com/search?language=ja-JP&q= as URL, because `?` separates path and query, and `&` generally separates elements in query.

**Comment by amalgame21** [comment]
Thanks for the tips, it works!!
