### ISSUE TITLE
Convert temperature

### ISSUE THREAD

**Issue by yephny** [nhirokinet/bluelineconsole#249]
Conversion between temperature units: fahrenheit, celcius, kelvin.

**Comment by yephny** [comment]
On that note, typing 0 celsius in fahrenheit takes much longer than 0f in c. Would single letter abbreviations work?

**Comment by nhirokinet** [comment]
No, to prevent confusion due to the same name in different area, Blue Line Console currently accepts one letter unit name only for SI units.

Thus, `K` works as kelvin, but no abbreviations for celsius or fahrenheit.

**Comment by yephny** [comment]
That makes sense, how about using the degree symbol? °F, °C, and, K.

**Comment by nhirokinet** [comment]
Just I didn't think of that, maybe  °F or °C can be added in later version with some additional consideration.

Currently unit names have only ASCII characters, but this is not technical nor policy reason, rather just avoided to add language-specific (like Japanese) words.
