### ISSUE TITLE
Calendar different color for today's date

### ISSUE THREAD

**Issue by foxonfox** [nhirokinet/bluelineconsole#251]
I use the `cal` command often. One thing that always found inconvenient was all the dates on the calender is same color.

If you could just give a different color to today's date it would be really helpful.

Example:
If I'm using old computer theme all dates will appear green. But today's date should appear in red.

**Comment by daffydock** [comment]
Agreed. I noticed the same thing. What I do now is open a calendar widget (depending on the Cal app you use) as a widget that I call "mycal." Under widgets commands in Config.

**Comment by foxonfox** [comment]
> Agreed. I noticed the same thing. What I do now is open a calendar widget (depending on the Cal app you use) as a widget that I call "mycal." Under widgets commands in Config.

I didn't know this launcher could load widgets. Now I'm loading the calendar the way you suggested. Thanks for sharing.

**Comment by daffydock** [comment]
@foxonfox You are very welcome. This is one of the best features of BlueLineConsole and I also use it to check my mail, subreddits and any other data that is availavoe via widgets. It all depends on the apps you have. I also open specific web links with an app that allows to create widgets out of them. You might find doing that useful, too. Cheers.

**Comment by nhirokinet** [comment]
Added highlight of today to `cal` command in version 1.2.15.

Availability on Google Play and F-Droid will take a time following the policy of each store.
