### ISSUE TITLE
Request for Chinese Pinyin Initial Letter Search Functionality

### ISSUE THREAD

**Issue by goxofy** [nhirokinet/bluelineconsole#281]
I would like to request your beautiful app to  support Chinese Pinyin initial letter search functionality. 
For example, when searching for "tb", the app should be able to return results for "淘宝"(Chinses Pinyin is Taobao), and when searching for "wx", the app should return results for "微信"(Chinese Pinyin is Weixin). 
This feature would greatly improve the usability of the app for Chinese-speaking users who are accustomed to using Pinyin to search for content. 
Thank you for your consideration.

**Comment by nhirokinet** [comment]
Duplicated #207
