### ISSUE TITLE
Show apps on home screen

### ISSUE THREAD

**Issue by SleepzCat** [nhirokinet/bluelineconsole#298]
It would be useful to have a feature that lets you show apps on the home screen by default like you can with widgets. Also the ability to choose to hide specific apps and prevent them from appearing in search results would be useful as well.

**Comment by nhirokinet** [comment]
> a feature that lets you show apps on the home screen by default like you can with widgets

You can add a command with full package name (like `net.nhiroki.bluelineconsole`) to home screen.

> the ability to choose to hide specific apps and prevent them from appearing in search results

Duplicated with #87 .
