### ISSUE TITLE
Ability to block some apps

### ISSUE THREAD

**Issue by AtaYalcin** [nhirokinet/bluelineconsole#301]
I am using this app as my default launcher for some while , it is totally wonderful. Some smartphone manufacturers(including mine) make some applications non-deletable, instead they add an option to hide it from their default launchers. bluelineconsole shall incorparate this functionality. As to give an example, i am using newpipe as my youtube client, as it does not have a personal recomendation feature, it helps me focus on my daily tasks rather than to spend countless hours watching meaningless videos. For my personal use ı have hardcoded to the source code to block youtube and created a personal apk. I can create a fork of this app to enable blocking functionality but i doubt that ı will be able to that in complience with the apps design language. Furthermore as an AI guy myself ı am not an expert in android and presumably such a fork will just rely on a text input with delimeters between app names. if i do such a primitive fork will you be able to merge it ? if this simple design wont be mergible then i shall wait untill this functionality is developed by another developer. Thank you in advance

**Comment by nhirokinet** [comment]
Duplicated with #87
