### ISSUE TITLE
[Feature Request] Startpage Search Engine

### ISSUE THREAD

**Issue by Samylol99** [nhirokinet/bluelineconsole#336]
Hi, I really like using this app it's a very good and finally an actually useful assistant for me.
I would appreiciate if you added the startpage search engine, since according to my research it's as privacy respecting if not better than DuckDuckGo and it gives much better result according to my experience with it. (Also its shortcut could just be 's')

**Comment by daffydock** [comment]
Simply add it yourself.

Use:
https://www.startpage.com/sp/search?query=

Click on the option to put the search item after it. Label it Starpage, use whatever shortcut you want.

**Comment by Samylol99** [comment]
Tysm. I somehow failed to notice I could do that. I appreciate your help. Closing the issue now.

**Comment by daffydock** [comment]
> Tysm. I somehow failed to notice I could do that. I appreciate your help. Closing the issue now.

Great to hear. Happy I was able to help.
