### ISSUE TITLE
[Bug] The console doesn't stay

### ISSUE THREAD

**Issue by puditracode** [nhirokinet/bluelineconsole#81]
When im moving the console to the edge or somewhere else on my screen and try to type something, it move back to its original position.

Can you fix that up?

And btw, thx for making this app!

**Comment by nhirokinet** [comment]
This is not a bug. When something is typed, window size will change, although not always. Not to go to untouchable area (out of the display), console will go back to original position.

Dragging window was implemented to read the content background temporarily, so once result is obtained I think it is normal to display all results in the display.

**Comment by nhirokinet** [comment]
It is explicitly called from the line below, and `BaseWindowActivity.setWindowBoundarySize()` resets padding size every time.

https://github.com/nhirokinet/bluelineconsole/blob/7decabf7a4011cfa6d7a0eff33f9d4fdaf6be629/app/src/main/java/net/nhiroki/bluelineconsole/applicationMain/MainActivity.java#L241

Remembering the offset while dragging in `BaseWindowActivity` and adding the offset in `setWindowBoundarySize()` can keep the window place, but in some cases this might cause confusing and unexpected behavior for user. So in this repository (not including fork, of course) and my releases, I will not add that function.
