### ISSUE TITLE
[feature request] support any uri

### ISSUE THREAD

**Issue by Kurty00** [nhirokinet/bluelineconsole#83]
Hey. I've been trying to add one time passwords to my 2fa app using the following uri format (which works in my browser) in blue line console:
 otpauth://totp/accountname?secret=someaccountsecret&digits=6&period=30

Although this is a valid URI, blue line console didn't open the app selection menu.

**Comment by nhirokinet** [comment]
I added an option to accept URI with any scheme in Advanced section in version 1.2.8.

This time the status in Google Play is "in review", so availability on Google Play and F-Droid will take a time according to each store's policy.
