### ISSUE TITLE
(Feature Request) Add an option to open keyboard with launching the app by default

### ISSUE THREAD

**Issue by nihalanand697** [nhirokinet/bluelineconsole#9]
Hi, loving the app really. Could you please make it possible so that the keyboard is opened automatically on app launch to make tyoing faster? :3

**Comment by nhirokinet** [comment]
Thanks for your comment!

I did not notice of this because my phone have physical keyboard. I think software keyboard should appear immediately after app launch by default.

I will try to open software keyboard automatically.

**Comment by nhirokinet** [comment]
Fixed it and uploaded to the Store. Thanks!
